spring:
  datasource:
    url: jdbc:mysql://localhost:3306/performance_manage?useUnicode=true&characterEncoding=utf8&useSSL=true&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

  resources:
    static-locations: classpath:/META-INF/resources/,classpath:/resources/,
      classpath:/static/, classpath:/static/dist/

  mvc:
    view:
      suffix: .html